model:
  types_map:
    bigint:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    dec:
      - type: float64
      - type: sql.Null[float64]
        is_default_null: true
        value: .V
    decimal:
      - type: float64
      - type: sql.Null[float64]
        is_default_null: true
        value: .V
    numeric:
      - type: float64
      - type: sql.Null[float64]
        is_default_null: true
        value: .V
    double:
      - type: float64
      - type: sql.Null[float64]
        is_default_null: true
        value: .V
    float:
      - type: float64
      - type: sql.Null[float64]
        is_default_null: true
        value: .V
    float4:
      - type: float64
      - type: sql.Null[float64]
        is_default_null: true
        value: .V
    float8:
      - type: float64
      - type: sql.Null[float64]
        is_default_null: true
        value: .V
    int:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    int1:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    int2:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    int3:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    int4:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    int8:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    integer:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    mediumint:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    middleint:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    smallint:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    tinyint:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    date:
      - type: time.Time
      - type: sql.Null[time.Time]
        is_default_null: true
        value: .V
    datetime:
      - type: time.Time
      - type: sql.Null[time.Time]
        is_default_null: true
        value: .V
    timestamp:
      - type: time.Time
      - type: sql.Null[time.Time]
        is_default_null: true
        value: .V
    time:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    year:
      - type: int64
      - type: sql.Null[int64]
        is_default_null: true
        value: .V
      - type: uint64
        is_unsigned: true
      - type: sql.Null[uint64]
        is_default_null: true
        is_unsigned: true
        value: .V
    bit:
      - type: byte
      - type: sql.Null[byte]
        is_default_null: true
        value: .V
      - type: byte
        is_unsigned: true
      - type: sql.Null[byte]
        is_default_null: true
        is_unsigned: true
        value: .V
    bool:
      - type: bool
      - type: sql.Null[bool]
        is_default_null: true
        value: .V
    boolean:
      - type: bool
      - type: sql.Null[bool]
        is_default_null: true
        value: .V
    char:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    varchar:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    nvarchar:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    nchar:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    character:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    longvarchar:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    linestring:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    multilinestring:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    binary:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    varbinary:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    tinytext:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    text:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    mediumtext:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    longtext:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    enum:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    set:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    json:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    blob:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    longblob:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    mediumblob:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
    tinyblob:
      - type: string
      - type: sql.Null[string]
        is_default_null: true
        value: .V
